print("              author Nakshatra Ranjan Saha           ")
print("                      cost - 25 $                    ")
print("                  Date - 02-03-2021                  ")
print("        Regestered To Mr Nakshatra Ranjan Saha       ")
print("    ____________________________________________     ")
print("   |                                            |    ")
print("   |  #####    ##        # ######  ####  #    # |    ")
print("   |  #    #  #  #       # #      #      #    # |    ")
print("   |  #    # #    #      # #####   ####  ###### |    ")
print("   |  #####  ######      # #           # #    # |    ")
print("   |  #   #  #    # #    # #      #    # #    # |    ")
print("   |  #    # #    #  ####  ######  ####  #    # |    ")
print("   |____________________________________________|    ")
print("      ________________________________________       ")
print("     |                                        |      ")
print("     |    Auther - Nakshatra Ranjan Saha      |      ")
print("     |________________________________________|      ")
      